# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            We already heard
tagline:          'A Jekyll theme'
description:      'Personal and professional musings, things you heard before. Made by <a href="https://twitter.com/entendu" target="_blank">@entendu</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Domenic Santangelo'
  url:            https://twitter.com/entendu

paginate:         5

# Custom vars
version:          1.0.0
gems: [jekyll-paginate, jekyll-gist]

github:
  repo:           https://github.com/poole/hyde
